[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dlbasics"
version = "0.1.0"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["deep-learning-basics/src"]
